# Generated by Django 4.2.4 on 2023-09-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                default="users/defaultcover.jpg",
                upload_to="users/cover_photos",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="users/defaultlogo.png",
                upload_to="users/profile_pictures",
            ),
        ),
    ]
